version: '3'

services:
  app:
    build: .
    container_name: newsrpa-app
    environment:
      - DATABASE_URL=mysql+pymysql://newsuser:ckd12345@외부DB주소:3306/news
      - SMTP_USER=${SMTP_USER:-ckdpharmamorning@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - APP_DOMAIN=pharmamorning.ckdpharm.com
      - SERVER_IP=10.4.31.151
    ports:
      - "8080:80"
    restart: always

  nginx:
    image: nginx:latest
    container_name: newsrpa-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/docker/data/mysql  # 윈도우 서버에 맞게 경로 수정 필요